### PR TITLE
Use helm as 'run' target dep instead of manifest

### PR DESCRIPTION
**Pull request by HartS**

### CODE REVIEW

**Review by mook-as — COMMENTED** [review]
This does mean it will rebuild all the time, though (because `helm` is `.PHONY`). Can we make it depend on a `.yml` instead?

**Comment by HartS** [comment]
Is there a reason to keep helm in .PHONY since `make helm` outputs a `helm/` directory?

**Comment by mook-as** [comment]
Yes, make is _completely_ busted WRT directories.  It just does the wrong thing all the time.

**Comment by HartS** [comment]
This has been amended to check for `helm/templates/uaa.yml` instead of just `helm/` now, so it will rebuild when `make helm` is called, and fail to `make run` if the helm template is not present.

**Review by mook-as — APPROVED** [review]
Sorry, this got lost. Basically fine, except it's now called `uaa.yaml` (with the `a`).

**Comment by HartS** [comment]
No longer needed/applicable

**Pull request closed without merging**
